### ISSUE TITLE
生成的二维码无法识别

### ISSUE THREAD

**Issue by zh-h** [aTool-org/chrome-qrcode#1]
![image](https://cloud.githubusercontent.com/assets/13273151/14585713/09570c46-04b1-11e6-8991-e370616f5b12.png)

Chrome 版本 48.0.2564.97

**Comment by zh-h** [comment]
这是V2EX的首页链接

**Comment by zh-h** [comment]
`Waiting for minutes ...`

**Comment by hustcc** [comment]
二维码贴错了吗？waiting for minutes出现这个可能是最近服务器被攻击导致的。这个问题在1.0.6版本中已经优化了。

**Comment by hustcc** [comment]
我个人测试是没有问题的~
