### ISSUE TITLE
zxing.min.js 有未压缩的版本吗？

### ISSUE THREAD

**Issue by 7iang** [aTool-org/chrome-qrcode#2]
老板，能否提供下zxing.min.js未混淆的版本？

**Comment by hustcc** [comment]
zxing 是开源项目，可以直接在 github 搜索即可。回复晚了，不好意思，之前可能没有 watch ，所以一直没有看到。

**Comment by 7iang** [comment]
能给个具体的github地址吗？搜索出来很多结果。。。

**Comment by hustcc** [comment]
我发现我的找不到了，我这个识别的代码，不知道是网上哪个demo抠出来的~
